### ISSUE TITLE
可以考虑将你的 PDF 转换为 VitePress ，做成在线版本的

### ISSUE THREAD

**Issue by Aurorxa** [godbasin/front-end-book#1]
如果需要，我可以帮忙提交 PR ；不过，感觉之前的 HTML、CSS 部分，太旧了；貌似也没必要注水。

**Comment by godbasin** [comment]
打算这么做，只留下 5-9 章的，不过处理的时候发现有些内容可能得调整下会更好，然后就搁置了~
后面等我有空处理下

**Comment by godbasin** [comment]
搞好啦
https://godbasin.github.io/front-end-book/getting-started/

**Comment by Aurorxa** [comment]
谢谢
