### ISSUE TITLE
找到一处笔误

### ISSUE THREAD

**Issue by acgotaku** [godbasin/front-end-book#2]
<img width="1137" alt="Screenshot 2024-08-15 at 9 50 53" src="https://github.com/user-attachments/assets/d2a0c5b8-39c2-4e33-a2b4-3f289c7ca986">

此处应该是 number

**Comment by godbasin** [comment]
好滴，不过 pdf 版本已经没得再改啦，前端部分的内容应该不少错别字，内容也有些滞后了，可以去我博客里看~~
谢谢反馈呀！

**Comment by acgotaku** [comment]
现在已经出了在线版了么？

**Comment by godbasin** [comment]
> 现在已经出了在线版了么？

在整理，流水线还没跑通，等有空再研究研究

**Comment by godbasin** [comment]
在线版整好了
https://godbasin.github.io/front-end-book/getting-started/

可以直接在里面提 MR 修改~
